
;-------------------------------------------------------------------------------

.data
defaultSpots WORD SPACE, DOT, ENERGIZER, NULL
ghostSpots   WORD SPACE, DOT, ENERGIZER, GHOST_DOOR, NULL

;-------------------------------------------------------------------------------

Position_validPosition PROTO
Position_movePoint PROTO

Position_validMove PROTO
Position_validChar PROTO

;-------------------------------------------------------------------------------
