
;-------------------------------------------------------------------------------
; Prototypes
;-------------------------------------------------------------------------------

Utils_digitToChar PROTO
Utils_bonusSymbolForLevel PROTO

Utils_seedRandom PROTO
Utils_randomValue PROTO

Utils_copyPoint PROTO
Utils_pointsEqual PROTO

Utils_clearKeys PROTO
Utils_reverseDirection PROTO

;-------------------------------------------------------------------------------
